rabbitmq:
  image: rabbitmq:3.5-management
  ports:
    - "15672:15672"  # management port (guest:guest)
    - "5672:5672"   # amqp port
    - "25672:25672" # cluster port

clamd:
  build: ./ukwa-clamd
  ports:
    - "3310:3310"

ukwa-heritrix:
  build: ./ukwa-heritrix
  volumes:
    - ./jobs:/jobs
    - ./output:/output
  ports:
    - "8443:8443"
  links:
    - rabbitmq
    - clamd

ukwa-webrender:
  build: ./ukwa-webrender
  ports:
    - "8000:8000"

ukwa-harchiverd:
  build: ./ukwa-harchiverd
  volumes:
    - ./output/images:/images
  links:
    - rabbitmq
    - ukwa-webrender

# To Add:
# a test server to crawl
# a tester process to talk to Heritrix, probably via python-heritrix

